"""Utility helpers that provide schema-aware metadata to grammars.

The helpers source schema information from the built-in DDL generator so that
SQL grammars can ask for valid table/column/value combinations without a live
PostgreSQL connection.  When the same DDL is applied to a database before
running the workload the generated queries will compile because every column
reference matches that schema.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
import random
import re
import uuid

from .ddl_generator import DDLGenerator, TableDefinition, ColumnDefinition, TableConstraint


@dataclass
class ColumnInfo:
    """Lightweight view of a table column"""

    name: str
    data_type: str
    nullable: bool
    has_default: bool
    unique: bool = False
    length: Optional[int] = None

    @property
    def base_type(self) -> str:
        """Return the normalized PostgreSQL type name"""
        dtype = self.data_type.lower()
        dtype = dtype.replace("generated by default as identity", "")
        dtype = dtype.replace("without time zone", "")
        dtype = dtype.replace("with time zone", "")
        dtype = dtype.strip()
        if "(" in dtype:
            dtype = dtype.split("(", 1)[0]
        return dtype.strip()

    @property
    def max_length(self) -> Optional[int]:
        return self.length


@dataclass
class TableInfo:
    """Schema information for a table"""

    name: str
    columns: Dict[str, ColumnInfo]
    primary_key: Optional[str]
    unique_columns: List[str]
    primary_key_columns: List[str] = field(default_factory=list)

    def insertable_columns(self) -> List[str]:
        cols: List[str] = []
        for column in self.columns.values():
            if column.name == self.primary_key and ("identity" in column.data_type.lower() or column.has_default):
                continue
            if column.name in {"created_at", "updated_at"} and column.has_default:
                continue
            cols.append(column.name)
        return cols

    def updateable_columns(self) -> List[str]:
        cols: List[str] = []
        for column in self.columns.values():
            if column.name in {self.primary_key, "created_at"}:
                continue
            cols.append(column.name)
        return cols

    def required_insert_columns(self) -> List[str]:
        cols: List[str] = []
        for column in self.columns.values():
            if column.nullable or column.has_default:
                continue
            if column.name == self.primary_key and "identity" in column.data_type.lower():
                continue
            cols.append(column.name)
        return cols


class SchemaCatalog:
    """Schema-aware, offline catalog and the primary interface for grammars.

    This catalog is the single, authoritative API for all schema-related
    questions inside PyRQG. It is "offline" by design: instead of connecting to
    a live database, it consumes structured table definitions produced by the
    built-in DDL generator. This makes the behavior deterministic and easy to
    test. Any generator/grammar that needs to know about tables, columns, data
    types, or how to produce values consistent with a column type should use
    this class.

    Key responsibilities and properties:
    - Maintains a normalized view of tables and columns via TableInfo/ColumnInfo
    - Provides helpers for picking tables and columns (insert/update-friendly)
    - Generates SQL literals consistent with column data types via value_for()
    - Produces simple WHERE/JOIN conditions consistent with the schema

    For environments that prefer live introspection, see
    pyrqg.online_catalog.OnlineSchemaCatalog which implements the same
    interface but loads table metadata from a database and then delegates to
    this class.
    """

    def __init__(self, tables: Dict[str, TableInfo]):
        if not tables:
            raise ValueError("SchemaCatalog requires at least one table")
        self.tables = tables
        self._column_map: Dict[str, List[str]] = {}
        for table, info in tables.items():
            for col in info.columns.keys():
                self._column_map.setdefault(col, []).append(table)

    @classmethod
    def from_table_definitions(cls, tables: List[TableDefinition]) -> "SchemaCatalog":
        """Build catalog from DDLGenerator table definitions"""
        table_map: Dict[str, TableInfo] = {}
        for table in tables:
            columns: Dict[str, ColumnInfo] = {}
            unique_cols: List[str] = []
            primary_key: Optional[str] = None
            primary_key_cols: List[str] = []

            table_unique = cls._extract_unique_columns(table)
            unique_cols.extend(table_unique)

            for column in table.columns:
                length = None
                match = re.search(r"(char(?:acter varying)?|varchar)\s*\((\d+)\)", column.data_type, re.IGNORECASE)
                if match:
                    try:
                        length = int(match.group(2))
                    except ValueError:
                        length = None
                col_unique = column.unique or column.name in table_unique
                if column.name == "id" and column.data_type.upper().startswith("INTEGER"):
                    # Most base tables define PK via constraint rather than inline unique
                    col_unique = True
                columns[column.name] = ColumnInfo(
                    name=column.name,
                    data_type=column.data_type,
                    nullable=column.nullable,
                    has_default=column.default is not None,
                    unique=col_unique,
                    length=length,
                )

            for constraint in table.constraints:
                if constraint.constraint_type == "PRIMARY KEY" and constraint.columns:
                    primary_key_cols = list(constraint.columns)
                    primary_key = primary_key_cols[0]

            table_map[table.name] = TableInfo(
                name=table.name,
                columns=columns,
                primary_key=primary_key,
                unique_columns=list(dict.fromkeys(unique_cols)),
                primary_key_columns=primary_key_cols,
            )
        return cls(table_map)

    @staticmethod
    def _extract_unique_columns(table: TableDefinition) -> List[str]:
        unique_cols: List[str] = []
        for constraint in table.constraints:
            if constraint.constraint_type == "UNIQUE" and constraint.columns:
                # Only mark single-column UNIQUEs as conflict targets
                if len(constraint.columns) == 1:
                    unique_cols.append(constraint.columns[0])
        return unique_cols

    @classmethod
    def default(cls, seed: Optional[int] = None) -> "SchemaCatalog":
        """Create a catalog from the built-in sample schema"""
        generator = DDLGenerator(seed=seed)
        tables = generator.generate_sample_tables()
        return cls.from_table_definitions(tables)

    def random_table(self, rng: random.Random) -> str:
        return rng.choice(list(self.tables.keys()))

    def random_table_with_columns(self, rng: random.Random, min_columns: int = 1) -> str:
        eligible = [name for name, info in self.tables.items() if len(info.columns) >= min_columns]
        return rng.choice(eligible or list(self.tables.keys()))

    def list_tables(self) -> List[str]:
        return list(self.tables.keys())

    def shared_columns(self, left: str, right: str) -> List[str]:
        return list(set(self.tables[left].columns.keys()) & set(self.tables[right].columns.keys()))

    def pick_insert_columns(self, table: str, rng: random.Random, min_cols: int = 2, max_cols: int = 5) -> List[str]:
        info = self.tables[table]
        base = info.insertable_columns()
        if not base:
            base = list(info.columns.keys())
        required = info.required_insert_columns()
        max_pick = max(1, min(max_cols, len(base)))
        min_pick = min(len(base), max(min_cols, len(required)))
        count = rng.randint(min_pick, max_pick) if max_pick >= min_pick else min_pick
        picks = list(required)
        remaining = count - len(picks)
        optional = [col for col in base if col not in picks]
        if remaining > 0 and optional:
            picks.extend(rng.sample(optional, min(remaining, len(optional))))
        elif remaining < 0:
            picks = rng.sample(picks, count)
        return picks

    def pick_update_columns(self, table: str, rng: random.Random, min_cols: int = 1, max_cols: int = 3) -> List[str]:
        info = self.tables[table]
        candidates = info.updateable_columns()
        if not candidates:
            candidates = list(info.columns.keys())
        count = rng.randint(min_cols, min(max_cols, len(candidates))) if candidates else 1
        return rng.sample(candidates, count)

    def required_insert_columns(self, table: str) -> List[str]:
        return self.tables[table].required_insert_columns()

    def numeric_column(self, table: str, rng: random.Random) -> Optional[str]:
        return self._column_by_type(table, rng, {"integer", "bigint", "smallint", "numeric", "decimal", "real", "double precision"})

    def text_column(self, table: str, rng: random.Random) -> Optional[str]:
        return self._column_by_type(table, rng, {"varchar", "text", "char", "character varying"})

    def boolean_column(self, table: str, rng: random.Random) -> Optional[str]:
        return self._column_by_type(table, rng, {"boolean"})

    def timestamp_column(self, table: str, rng: random.Random) -> Optional[str]:
        return self._column_by_type(table, rng, {"timestamp", "timestamptz", "date", "time", "timetz"})

    def json_column(self, table: str, rng: random.Random) -> Optional[str]:
        return self._column_by_type(table, rng, {"json", "jsonb"})

    def _column_by_type(self, table: str, rng: random.Random, allowed: set[str]) -> Optional[str]:
        info = self.tables[table]
        candidates = [name for name, col in info.columns.items() if col.base_type in allowed]
        return rng.choice(candidates) if candidates else None

    def conflict_target(self, table: str) -> Optional[str]:
        info = self.tables[table]
        if info.primary_key:
            return info.primary_key
        if info.unique_columns:
            return info.unique_columns[0]
        return None

    @staticmethod
    def _limit_literal(literal: str, max_len: Optional[int]) -> str:
        if max_len is None:
            return literal
        if literal.startswith("'") and literal.endswith("'"):
            inner = literal[1:-1]
            if len(inner) <= max_len:
                return literal
            return f"'{inner[:max_len]}'"
        return literal

    def value_for(self, table: str, column: str, rng: random.Random) -> str:
        info = self.tables[table]
        col = info.columns[column]
        base = col.base_type
        name = column
        max_len = col.max_length
        numeric_integral = {"integer", "bigint", "smallint"}
        numeric_fractional = {"numeric", "decimal", "real", "double", "double precision"}
        text_types = {"varchar", "text", "char", "character varying"}

        if base in numeric_integral:
            return str(rng.randint(1, 1_000_000))
        if base in numeric_fractional:
            return f"{rng.randint(1, 10000)}.{rng.randint(0, 99):02d}"
        if base == "boolean":
            return rng.choice(["true", "false"])
        if base in {"timestamp", "timestamptz", "time", "timetz"}:
            return "CURRENT_TIMESTAMP"
        if base == "date":
            return "CURRENT_DATE"
        if base == "uuid":
            return f"'{uuid.uuid4()}'"
        if base in {"json", "jsonb"}:
            return "'{}'::jsonb"
        if base.endswith("[]"):
            return "ARRAY['item1','item2']"
        if base == "inet":
            octets = [str(rng.randint(1, 254)) for _ in range(4)]
            return "'" + ".".join(octets) + "'::inet"

        if name.endswith("_id") or name in {"quantity", "count", "score", "age"}:
            if base in numeric_integral or base in numeric_fractional:
                return str(rng.randint(1, 1000))
            literal = f"'id_{rng.randint(1, 1_000_000)}'"
            return self._limit_literal(literal, max_len)
        if name in {"price", "amount", "total", "balance", "tax", "discount"}:
            return f"{rng.randint(10, 5000)}.{rng.randint(0, 99):02d}"
        if name == "email":
            user = rng.choice(["alice", "bob", "charlie", "dana"])
            domain = rng.choice(["example.com", "test.dev"])
            literal = f"'{user}{rng.randint(1,999)}@{domain}'"
            return self._limit_literal(literal, max_len)
        if name in {"first_name", "last_name", "name", "username"}:
            literal = rng.choice(["'Alice'", "'Bob'", "'Charlie'", "'Daphne'"])
            return self._limit_literal(literal, max_len)
        if name in {"status", "state", "type", "role", "category"}:
            literal = rng.choice(["'active'", "'inactive'", "'pending'", "'archived'"])
            return self._limit_literal(literal, max_len)
        if name.endswith("_at"):
            return "CURRENT_TIMESTAMP"
        if name in {"data", "metadata", "properties"}:
            return "'{}'::jsonb"
        literal = f"'value_{rng.randint(1, 1_000_000)}'"
        return self._limit_literal(literal, max_len)

    def where_condition(self, table: str, rng: random.Random) -> str:
        info = self.tables[table]
        numeric = [col for col in info.columns if info.columns[col].base_type in {"integer", "bigint", "smallint", "numeric", "decimal", "real", "double precision"}]
        text = [col for col in info.columns if info.columns[col].base_type in {"varchar", "text", "char", "character varying"}]
        boolean = [col for col in info.columns if info.columns[col].base_type == "boolean"]
        parts: List[str] = []
        if numeric:
            col = rng.choice(numeric)
            op = rng.choice(["=", ">", "<", ">=", "<=", "<>"])
            parts.append(f"{col} {op} {rng.randint(1, 1000)}")
        if text and rng.random() < 0.4:
            col = rng.choice(text)
            parts.append(f"{col} = {self.value_for(table, col, rng)}")
        if boolean and rng.random() < 0.2:
            col = rng.choice(boolean)
            parts.append(f"{col} = {rng.choice(['true', 'false'])}")
        if not parts:
            pk = info.primary_key or "id"
            return f"{pk} > {rng.randint(0, 100)}"
        if len(parts) == 1:
            return parts[0]
        return f"{parts[0]} AND {parts[1]}"

    def join_condition(self, left: str, right: str, rng: random.Random) -> Optional[Tuple[str, str]]:
        left_cols = self.tables[left].columns
        right_cols = self.tables[right].columns
        shared = set(left_cols.keys()) & set(right_cols.keys())
        preferred = [col for col in shared if col.endswith("_id") or col == "id"]
        if preferred:
            col = rng.choice(preferred)
            return col, col
        if shared:
            col = rng.choice(list(shared))
            return col, col
        # Look for *_id vs parent id
        for lcol in left_cols:
            if lcol.endswith("_id"):
                base = lcol[:-3] if lcol.endswith("_id") else lcol
                parent = f"{base}s"
                if self.tables[right].primary_key and self.tables[right].primary_key == "id" and right == parent:
                    return lcol, "id"
        return None


_catalog: Optional[SchemaCatalog] = None


def get_schema_catalog() -> SchemaCatalog:
    """Return a cached schema catalog"""
    global _catalog
    if _catalog is None:
        _catalog = SchemaCatalog.default(seed=42)
    return _catalog
